### ISSUE TITLE
Can I add to a site I am working on?

### ISSUE THREAD

**Issue by Piplup7575** [Jcw87/c2-sans-fight#127]
Hey Jcw87!
I work on a game site with 3kh0 (https://github.com/3kh0/3kh0.github.io) which has several thousand people accessing it a day.
A few people have requested that we add this game to the site, but I saw that you don't want there to be 1000 clones of this, so I was wondering if it would be ok if we put this on the site, as long as we give very clear credit and update it every time you update it?
Thanks!
-Piplup7575

**Comment by Jcw87** [comment]
I'm fine with a link or an embed. I'm not fine with you hosting the files.

I find it surprising that so many people have the goal of bypassing school firewalls, and the only solution they can think of is to re-host all of the things elsewhere on the internet, and hope the firewall won't pick up on it for a while. This is not a good strategy, as the firewall block lists are continuously updated by the firewall manufacturer to include any new sites that they find out about. If it's on the public internet, either the manufacturer or one of the many schools/companies they service will find it eventually, and then you will have to host it somewhere else. It's a never-ending cat and mouse game. I prefer solutions that I don't have to continuously re-visit.

You could run the game locally with any HTTP server. No school firewall will stop that, only excessively locked down computers could do so. In my experience, they never locked it down so hard that you couldn't get downloaded programs to run. Installers usually don't work, as most of them will ask for Administrator access to run, but applications that don't require installation or Administrator access work just fine.

You could create a private SOCKS proxy on your home internet connection, and use it to unlock the whole internet. Since it is private, the number of people who could find out about it shrinks dramatically, and so does the chance that it gets blocked.

**Comment by Piplup7575** [comment]
> find it eventually, and then you will have to host it somewhere else. It's a never-ending cat and mouse game. I prefer solutions that I don't have to continuously re-visit.

I do too, I run the site locally for my use only, but I know a lot of people who use this as they have no clue how to self host, hence our discord server mostly being people trying to find unblocked links/being confused af about how to self host
Most people use the site on chromebooks, so self hosting doesn't work.

Thanks for your help anyways!


> they never locked it down so hard that you couldn't get downloaded programs to run

Heh, you haven't seen my school systems chromebooks.
