### ISSUE TITLE
Shift ends the battle when playing a single attack

### ISSUE THREAD

**Issue by OffifialMITX** [Jcw87/c2-sans-fight#13]

**Comment by Jcw87** [comment]
This is intended for single-attack mode. I wanted a way to stop the attack, so that I could start it over if something went wrong with it. This is also useful for anyone seeking to make their own attack. In addition, I thought it would also be useful for players who get bored of dodging an attack and don't want to commit suicide.

**Comment by OffifialMITX** [comment]
But you can already exit with **X** and on a compact keyboard layput like mine it's way too easy to hit shift accidenteley.

**Comment by Jcw87** [comment]
No action in this game is controlled directly by any button or key, but instead maps to a 'virtual gamepad', which then handles all player interaction. Originally, only 'Z' and 'X' were 'accept' and 'cancel', but someone complained that Undertale also supported 'Space' and 'Shift', so I added those as alternates for 'Z' and 'X'.

The only thing regarding key mappings that really should be changed is the mapping of 'Space' to 'confirm', as it really should be 'Enter' like the actual game. 'Shift' is going to remain as 'cancel'.
