### ISSUE TITLE
Wii u internet browser

### ISSUE THREAD

**Issue by amhooman** [Jcw87/c2-sans-fight#143]
So I tried this game on wii u internet browser, as a joke, and it actually worked! besides one small problem. I can't start the game without the space bar. Can you please make it so menus can be interacted with touch? The d pad of the wii u can already control the first menu. Thanks

**Comment by Jcw87** [comment]
I added a hack that treats the WiiU browser as a mobile device to make the mobile touch buttons show up, but since the WiiU browser doesn't support webgl, it uses html5 canvas rendering, and is really slow. The framerate makes it unplayable. It isn't worth keeping this single-device hack if that single device can't keep up.
