### ISSUE TITLE
[Gfx] Improve Gaster Blasters

### ISSUE THREAD

**Issue by OffifialMITX** [Jcw87/c2-sans-fight#28]
This is the only thing left which makes it easy to see if this is the original fight or not, and while it doesn't affect gameplay at all, it just doesn't look really good.

**Comment by Jcw87** [comment]
Fixed.

**Comment by iKNIFEu** [comment]
h m m m . . .
w h a t a b o u t t h i s ?
![image](https://user-images.githubusercontent.com/58735494/104192017-53240e00-542f-11eb-846e-0ecc57d0102a.png)

**Comment by MrHeating** [comment]
> Sorry it took so long to catch that damned image for the gaster blaster because they're fast af

You could also have taken a recording of the screen and take the picture after the fact. E.g. with [OBS](https://obsproject.com).

**Comment by iKNIFEu** [comment]
I'm lazy af dw about it bruv

**Comment by MrHeating** [comment]
Either way what is your OS, browser and hardware? 'Cause it works fine on my end.

**Comment by iKNIFEu** [comment]
My OS? Windows 10, I use google chrome.
And my PC is trash because I put too many duplicates of this simulator.
It took me days to mod a simulator with remastered stuff.

**Comment by Jcw87** [comment]
@iKNIFEu The math I perform for positioning the white boxes checks out, so I can only chalk this up to rounding error. If I attempt to compensate for it by making one of the boxes bigger, a different problem occurs when the beam fades out

![image](https://user-images.githubusercontent.com/975426/104404851-7d013180-5510-11eb-8519-fcc0f8a9a842.png)

Also, this issue was originally about the gaster blaster beams only being 1 box instead of 3 and has been fixed already. Any further problems with the gaster blaster appearance should be a new issue.

**Comment by iKNIFEu** [comment]
alright.

**Comment by CJTHEGAMER** [comment]
Y'all are picky lol

**Comment by MrHeating** [comment]
> If I attempt to compensate for it by making one of the boxes bigger, a different problem occurs when the beam fades out

Couldn't you make all of the objects' final form count as one and apply alpha to that? Also why's it gotta be separate objects anyway? Isn't it basically just a line with different thicknesses at different parts?

> Y'all are picky lol

Well the goal is to be as close as feasible, I dunno what you expect.

**Comment by Jcw87** [comment]
Construct 2 doesn't give you much control over rendering. Your base rendering operation is having an instance of an object present in the game world. Exactly how that object gets rendered is up to the plugin that implements the object, but the default plugins doesn't get any more complicated than drawing some textured quads. You can set a blend mode on an object, and add fragment shaders. That's it.

To assist with z-order management, you can create layers. Each layer can also have a blend mode and shaders, and you can force the layer to render to a texture so that the whole layer is blended at once. This isn't a viable solution, however, as you cannot create layers at runtime. You either put all gaster blasters on one layer and lose the ability to control their opacities individually, or you create so many layers that it becomes an organizational nightmare (and likely kills performance on mobile GPUs).

There are two third party plugins that are designed for more advanced drawing. One of them only works with software html5 canvas rendering, and the other only works with WebGL rendering. To support both, I would need to use both plugins and create separate but equal drawing routines for them. There may also be additional issues with performance when many gaster blasters on screen at the same time. I recall using the WebGL one to test out a four-way splitscreen concept, and performance quickly became a concern.

Another option would be to use just 1 object, but with a shader that creates the required shape. This would work, but it would make this yet another thing that is different if you are unfortunate enough to have a GPU driver that is blacklisted or marked as having a "Major Performance Caveat" by your browser.

Another option would be to use 1 object with a texture that looks like the gaster blast. It would have to be a really big texture though, and seems like a waste of memory.

**Comment by MrHeating** [comment]
Does that mean you can't just draw a non-image shape without using shaders? I figured it'd be easy enough to draw a shape with 12 vertices and simply move them in a relative manner, if there's native support for that.

What about using a static image and simply stretching the last (few) pixel(s) as far as needed?
