### ISSUE TITLE
Blue soul error

### ISSUE THREAD

**Issue by Sansical** [Jcw87/c2-sans-fight#5]
Alright, this might be just a minor issue, but to me I think it should be fixed. When you jump with the blue soul and it hits the ground, if you were holding down the up button the soul won't go up again once it hits the ground, and you have to press up again. Just thought that pointing out this issue might be a good idea.

**Comment by Jcw87** [comment]
This is intentional. It is also intentional that you can't cheese the slam attacks by holding all arrows down.

**Comment by OffifialMITX** [comment]
What about just deactivating it for the bonestab attacks?

**Comment by Jcw87** [comment]
Why, exactly?

I'm very critical of fan-games that half-ass the primary mechanics. Automatic bunnyhop from holding the jump button is one of the signs of half-assed mechanics. Why should I lower my standards?

**Comment by OffifialMITX** [comment]
Okay, to half-ass is a very interesting verb I've never heard before, so do you mean like changing mechanics?
In case you do:
- It's how it works in the original
- It's not something you'll have the time to play with during the attacks anyways
- It makes some attacks easier to dodge, e.g:
- - platform blaster if you're falling towards the bottom and a new blaster comes there
- - Bonegap, if there are several parts with max. height comming
- - The part of multi with two platforms above each other and a bone from each side - you have to perfectly time the jump for the moment you touch the bottom
- - I guess you know that in the original version of final bonestab it's impossible to dodge it if you are thrown into the same dirrection multiple times and are __not__ holding down the correct button

Correct me if I gott you wrong.

**Comment by Jcw87** [comment]
To half-ass something means to perform a task, but without the care and effort that the task requires.



That may be how it worked in the original, but I strongly disagree with it. Toby Fox may have designed a great game, but his programming skills aren't exactly top notch.

How many great platformers have you played that allowed you to jump repeatedly by just holding the button? None that I can think of. How many fangames for those same platformers allowed you to do it? A good chunk of them, and it was a pretty good indicator that the creator either wasn't a very good programmer, or put no effort into the game.

**Comment by OffifialMITX** [comment]
Well ok, I got your point now, but: EVERY platformer I've played (unless you can call Portal a platformer) allows to auto-jump when touching the ground if you press jump 0.5 - 1 s before you land.

Btw, auto bunnyhop isn't necessarily a matter of bad programming. For example in Blender you have to make extra setting in order to allow that.

**Comment by Jcw87** [comment]
I'm not sure what platformers you are playing, but I just tried this in Super Mario Bros running at 12% speed, and could not get Mario to jump if I pressed the jump button before he landed. There is a thing that some platformers do where they allow you to jump for a short time after walking off a platform. Maybe this is what you were thinking of?

I've never seen any fangames made with Blender. The game engines most commonly used for fangames don't have a checkbox for this sort of thing on their built-in platforming behaviors. Many fangame authors just don't understand how game engines work in general, so whenever they need to add game logic that isn't part of some predefined behavior, they tend to create logic that is only intended to run once for a given event, but it ends up running multiple times, depending on how long the conditions are true. I recall this one Sonic fangame where you played as Dr Eggman (because good Sonic physics are hard, but 8-directional vehicle movement is BUILT IN!), and their terrible programming meant that you got an extra life for every game tick that you had 100 rings. So, collect exactly 100 rings and do nothing for a few seconds, and now you have practically infinite lives.

**Comment by OffifialMITX** [comment]
I'm not playing platformers anymore, but I remember that it is definitely possible to do what I've described in Supertux. It's like the open source mario with some addtitional game mechanics like dragging colored lamps to activate the belonging tiles.

Anyways, if you really think that imlementing this feature makes you look like a bad programmer then there are no more arguments I can come up with.

**Comment by OffifialMITX** [comment]
Wait no! I DO have an argument: Geometry Dash! I don't think I have to explain why.
