### ISSUE TITLE
"sans_spare" attack doesn't do anything

### ISSUE THREAD

**Issue by MasterGamingYT** [Jcw87/c2-sans-fight#58]
Your SOUL simply goes in and out of the bullet board during this attack

**Comment by Jcw87** [comment]
That's exactly the point though. That attack is used when sans is taking a break (sparing you) and you do something other than ATTACK, which would make it his turn without advancing the fight. The original game did this too (for ACT or ITEM).

If you were expecting it to be the player kill attack that happens when you also SPARE, that isn't in this version of the game. That attack serves more of a story purpose than a gameplay purpose, so I deliberately chose to not include it. This is why the text says he's taking a break, as opposed to sparing you.

**Comment by iKNIFEu** [comment]
> That's exactly the point though. That attack is used when sans is taking a break (sparing you) and you do something other than ATTACK, which would make it his turn without advancing the fight. The original game did this too (for ACT or ITEM).
> 
> If you were expecting it to be the player kill attack that happens when you also SPARE, that isn't in this version of the game. That attack serves more of a story purpose than a gameplay purpose, so I deliberately chose to not include it. This is why the text says he's taking a break, as opposed to sparing you.

Sorry for disturbance. But I can tell you how to do that.
![image](https://user-images.githubusercontent.com/58735494/79049975-369c4080-7c27-11ea-984a-d24129dd0bee.png)
That's all.

**Comment by Jcw87** [comment]
I don't need you to tell me how to add it. I deliberately chose not to.
