### ISSUE TITLE
How to change these files into an html file?

### ISSUE THREAD

**Issue by Blacite** [Jcw87/c2-sans-fight#63]
I download the .zip file and unzip it. But I don't know what to do next. I don't want to play the game on the browser every time.

**Comment by Blacite** [comment]
I mean how to play the game without Internet

**Comment by Jcw87** [comment]
The "browser ready" files are on the gh-pages branch. If you have difficulty in running it, it is because of the arbitrary restrictions that web browsers put on local files. All you need to work around these restrictions is to serve the game via any HTTP server. [Here's a big list of them.](https://en.wikipedia.org/wiki/Comparison_of_web_server_software)
