### ISSUE TITLE
Readme.md's Facepunch contact is deleted?

### ISSUE THREAD

**Issue by iKNIFEu** [Jcw87/c2-sans-fight#65]
In readme.md, I tried clicking face punch to contact you there, but it said account wasn't found.
is it just me, or did you really delete your account in face punch?
You may close this if you want, but you I really need you to delete Facepunch from the readme.md.
Sorry for any disturbance.

**Comment by Jcw87** [comment]
I didn't delete my account. Facepunch Studios closed down their forums some time ago. Some of the community moved to knockout.chat, but they are using a custom forum system that has no "private messaging", which makes it useless for directly contacting 1 person. I believe the reason they don't have a "private messaging" system is because such systems were never truly "private", as the administrator can just browse the database and see all messages in plain text. This is probably why many sites call them "direct messages" now instead of "private messages"

I'll leave this open as a reminder to change the readme.

**Comment by iKNIFEu** [comment]
Okay, thanks.

**Comment by Jcw87** [comment]
I've addressed the Facepunch  forum closure in the readme.
