### ISSUE TITLE
can i use your engine and clone?

### ISSUE THREAD

**Issue by vinnoso** [Jcw87/c2-sans-fight#81]
hello jcw87, i want to know if i can use your engine and clone it

and if i can, how i do that?

**Comment by israelita95** [comment]
Yeah, me too

**Comment by Jcw87** [comment]
Anything you make using this repository needs to be sufficiently different from it. Use different graphics, or attacks, or characters. I don't want a scenario where there are 500 different rehosts of the same thing, and nobody can find the most up to date version.

**Comment by israelita95** [comment]
I know what you're referring to ... but I mean this, how am I going to
create another BTS-like site and change the scene and the sprites? this
interfering with the original.

Em seg, 2 de nov de 2020 15:18, Jcw87 <notifications@github.com> escreveu:

**Comment by israelita95** [comment]
HOW I CLONE IT

Em seg, 2 de nov de 2020 15:20, XSwapF⃞ e⃞ l⃞ l⃞ <erickkawa5000@gmail.com>
escreveu:

**Comment by lin0de** [comment]
> Anything you make using this repository needs to be sufficiently different from it. Use different graphics, or attacks, or characters. I don't want a scenario where there are 500 different rehosts of the same thing, and nobody can find the most up to date version.

This game is popular on school computers and blocked on school computers.
So we rehost it so it doesn't get blocked. Cry about it dude.

**Comment by Jcw87** [comment]
> > Anything you make using this repository needs to be sufficiently different from it. Use different graphics, or attacks, or characters. I don't want a scenario where there are 500 different rehosts of the same thing, and nobody can find the most up to date version.
> 
> This game is popular on school computers and blocked on school computers. So we rehost it so it doesn't get blocked. Cry about it dude. (although we don't make money off of github pages thankfully)

Setting aside the question of whether you even _should_ subvert a school firewall, you don't need to rehost it on the internet to get around a school firewall. You can literally spin up a local http server with all the files on it, and no firewall would be able to stop it. Since that local http server would be inaccessible from the internet, I would be perfectly fine with it. It's really easy to do. I'll even spell it out for you.

1. Download [nginx](http://nginx.org/download/nginx-1.21.6.zip) and extract it somewhere.
2. Download the [gh-pages branch of this repository as a zip](https://github.com/Jcw87/c2-sans-fight/archive/refs/heads/gh-pages.zip) and extract its contents to the html folder inside the nginx folder
3. To work around potential issues with windows firewall, edit the `nginx.conf` file inside the `conf` folder and change the line that says `listen 80` to `listen 127.0.0.1:80`
4. Start the `nginx.exe` program.
5. Go to http://localhost/ in your web browser
6. Play game.

Put that effort on to a usb flash drive, and you have a portable Bad Time Simulator.
