### ISSUE TITLE
Sans Dialogue

### ISSUE THREAD

**Issue by iKNIFEu** [Jcw87/c2-sans-fight#89]
Can't you add a setting for putting the original text in?
Like, in the menu, you can go to settings, and set a boolean for TEXT or not.
I'm able to help you with the original text.
If you want to, I can just put the entire original text WITH the code you need.

**Comment by Jcw87** [comment]
The original sans dialog needs to have the context of the player performing the whole genocide run. Otherwise, it doesn't really have the same impact. It has never been about not having the text or not knowing how to do it. I do this out of respect for the game's writing. This was only ever meant as a way to play or practice the fight without murdering everyone

**Comment by iKNIFEu** [comment]
Alright.
