### ISSUE TITLE
I'm not a profesional, but....

### ISSUE THREAD

**Issue by HuntertheWhale** [Jcw87/c2-sans-fight#9]
I was thinking (you don't have to do this) that you could make a click and drag attack animator for non-professionals to make attacks with. It would be great and, heck, I'll start making streams about the attscks i make. ;) 👍

**Comment by Jcw87** [comment]
Making an editor is time consuming, and I'm not really interesting in spending that much more time on this project. I'll fix bugs if I can reproduce them, and I might even add an enhancement or two, but an editor is too much. Besides, it probably wouldn't work the way you are envisioning it. Making attacks (in the game's current state) is more comparable to programming than animating.

One of the reasons I haven't documented it yet, is because there are certain usability problems with it, and while I was willing to deal with them, I don't want to subject other people to them. If I were to document it now, people would have an expectation of backwards compatibility, which would hinder efforts to fix the usability problems.

**Comment by HuntertheWhale** [comment]
Okey Dokey. Whatevers fine with you. If you feel like it you can make a
list of commands for the custom attacks
